#%RAML 1.0 Trait
usage: Use this trait for Client ID Enforcement

#Adding client id and client secret as http headers to allow only authorized applications to access the APIs.

headers: 
  client_id:
    type: string
    required: true
    example: 6433d0b931b24820ad8698e690e98009
  client_secret:
    type: string
    required: true
    example: 0148851a7Da84C1E9d66FccE2987B8fc
responses:
  401:
    description: |
              Unauthorized.